send SIGALRM to ldap process if it is not stopped by /etc/init.d/slapd stop command

diff --git a/DEBIAN/postinst b/DEBIAN/postinst
--- a/DEBIAN/postinst
+++ b/DEBIAN/postinst
@@ -1279,7 +1279,7 @@ function configure_openldap()
 #	fi
 	## place schema extension
 
-	if [ -z "${OPENLDAP_POPULATED}" ] || ["${OPENLDAP_POPULATED}" == "false" ]; then
+	if [ -z "${OPENLDAP_POPULATED}" ] || [ "${OPENLDAP_POPULATED}" == "false" ]; then
 		log "Populating the LDAP database for the first time"
 
 		if ! (sudo ldapsearch -Y EXTERNAL -H ldapi:///  -b 'cn={1}cosine,cn=schema,cn=config' >/dev/null 2>&1 ); then
@@ -1516,8 +1516,16 @@ function configure_openldap()
 	log "Stopping slapd"
 	if (pidof slapd  >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
 		if ! (/etc/init.d/slapd stop   >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
-			log "Unable to stop slapd."
-			exitWithFailureCode 78
+			if ! (kill -s ALRM `cat /var/run/slapd/slapd.pid`   >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+				
+				log "Unable to stop slapd."
+				exitWithFailureCode 78
+			else
+				if (pidof slapd  >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+					log "Unable to stop slapd."
+					exitWithFailureCode 78	
+				fi
+			fi
 		fi        	
 	else
 		log "Slapd not running"
