Adjust the code to use the LE certificate path.

diff --git a/DEBIAN/postinst b/DEBIAN/postinst
--- a/DEBIAN/postinst
+++ b/DEBIAN/postinst
@@ -101,7 +101,7 @@ JAVA_KEYSTORE=${JDK_HOME}/jre/lib/security/cacerts
 LDAP_USER=openldap
 CILOGON_CERTS="cilogon-basic.pem cilogon-silver.pem cilogon-openid.pem"
 SSL_CERT_DIR=/etc/ssl/certs
-SSL_SERVER_KEY_DIR=/etc/ssl/private/
+#SSL_SERVER_KEY_DIR=/etc/ssl/private/
 D1_LOG_DIR=/var/log/dataone
 D1_LOG_FILE=dataone-cn-os-core.install.log
 D1_TMP_DIR=/tmp
@@ -110,6 +110,7 @@ D1_DEB_CONF_XML="d1DebConfig.xml"
 D1_DEB_XSD_URL="https://repository.dataone.org/software/cicore/trunk/d1_schemas/dataoneDebPkgConfigTypes.xsd"
 D1_DEB_XSD="dataoneDebPkgConfigTypes.xsd"
 SUCCESS=0
+SERVER_SSL_PREFIX_DIR=/etc/letsencrypt/live
 
 #positions of the flags in XML_TEMPLATE_FLAGS and DEB_QUESTION_FLAGS
 SEEN=0
@@ -735,8 +736,9 @@ function configure_node_properties_file()
 	configure_node_property "cn.router.nodeId" $NODE_PROPS
 	configure_node_property "cn.router.hostname" $NODE_PROPS
 	
+	local HOST_NAME=${DEB_QUESTION_VALUES[dataone-cn-os-core/cn.hostname]}
 	PUBLICCERT_VALUE=${DEB_QUESTION_VALUES[dataone-cn-os-core/cn.server.publiccert.filename]}
-	CERT_FILE_PATH=${SSL_CERT_DIR}/${PUBLICCERT_VALUE}
+	CERT_FILE_PATH=${SERVER_SSL_PREFIX_DIR}/${HOST_NAME}/${PUBLICCERT_VALUE}
 	CERT_FILE_PATH_ESC=${CERT_FILE_PATH//\//\\\/}
 	log "Public cert filename is: ${CERT_FILE_PATH_ESC}"
 	configure_node_property "cn.server.publiccert.filename" $NODE_PROPS "${CERT_FILE_PATH_ESC}"
@@ -801,15 +803,15 @@ function configure_certificates()
 	# check if this is a new install
 		
 	log "Start configuration of DataONE private key"
-	
-	if [ ! -e "${SSL_SERVER_KEY_DIR}/${DEB_QUESTION_VALUES[dataone-cn-os-core/cn.server.privatekey.filename]}" ];then
-		log "Key file is missing.  Please provide it as ${SSL_SERVER_KEY_DIR}/${DEB_QUESTION_VALUES[dataone-cn-os-core/cn.server.privatekey.filename]}. Without
+	local HOST_NAME=${DEB_QUESTION_VALUES[dataone-cn-os-core/cn.hostname]}
+	if [ ! -e "${SERVER_SSL_PREFIX_DIR}/${HOST_NAME}/${DEB_QUESTION_VALUES[dataone-cn-os-core/cn.server.privatekey.filename]}" ];then
+		log "Key file is missing.  Please provide it as ${SERVER_SSL_PREFIX_DIR}/${HOST_NAME}/${DEB_QUESTION_VALUES[dataone-cn-os-core/cn.server.privatekey.filename]}. Without
 		this, SSL will not function properly."
 		exitWithFailureCode 63
 	fi
 	
-	if [ ! -e "${SSL_CERT_DIR}/${DEB_QUESTION_VALUES[dataone-cn-os-core/cn.server.publiccert.filename]}" ]; then
-		log "Server Public Certificate file is missing.  Please provide it as ${SSL_CERT_DIR}/${DEB_QUESTION_VALUES[dataone-cn-os-core/cn.server.publiccert.filename]}. Without
+	if [ ! -e "${SERVER_SSL_PREFIX_DIR}/${HOST_NAME}/${DEB_QUESTION_VALUES[dataone-cn-os-core/cn.server.publiccert.filename]}" ]; then
+		log "Server Public Certificate file is missing.  Please provide it as ${SERVER_SSL_PREFIX_DIR}/${HOST_NAME}/${DEB_QUESTION_VALUES[dataone-cn-os-core/cn.server.publiccert.filename]}. Without
 		this, SSL will not function properly."
 		exitWithFailureCode 64
 	fi
@@ -901,13 +903,14 @@ function configure_keystore()
 
 	# output from keytool is piped to exit 0 so that if keytool fails due to the file already having
 	# been added then the postinst script does not fail due to the subshell failing
-	local INTERMEDIATE_BUNDLE="${DEB_QUESTION_VALUES[dataone-cn-os-core/cn.server.cachain.filename]}"
+	# After we switched to use LE certificates, it is not necessary to import its certificates to the java key store anymore since they are there.
+	#local INTERMEDIATE_BUNDLE="${DEB_QUESTION_VALUES[dataone-cn-os-core/cn.server.cachain.filename]}"
 	
-	log "Attempting to remove ${SSL_CERT_DIR}/${INTERMEDIATE_BUNDLE} from Java keystore: ${JAVA_KEYSTORE}"
-	(keytool -delete -noprompt -alias ${INTERMEDIATE_BUNDLE} -keystore ${JAVA_KEYSTORE} -storepass ${JAVA_KEYSTORE_PASSWORD} >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1 | exit 0)
+	#log "Attempting to remove ${SSL_CERT_DIR}/${INTERMEDIATE_BUNDLE} from Java keystore: ${JAVA_KEYSTORE}"
+	#(keytool -delete -noprompt -alias ${INTERMEDIATE_BUNDLE} -keystore ${JAVA_KEYSTORE} -storepass ${JAVA_KEYSTORE_PASSWORD} >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1 | exit 0)
 	
-	log "Adding ${SSL_CERT_DIR}/${INTERMEDIATE_BUNDLE} to Java keystore: ${JAVA_KEYSTORE}"
-	(keytool -importcert -noprompt -alias ${INTERMEDIATE_BUNDLE} -file ${SSL_CERT_DIR}/${INTERMEDIATE_BUNDLE} -keystore ${JAVA_KEYSTORE} -storepass ${JAVA_KEYSTORE_PASSWORD} >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1 | exit 0)
+	#log "Adding ${SSL_CERT_DIR}/${INTERMEDIATE_BUNDLE} to Java keystore: ${JAVA_KEYSTORE}"
+	#(keytool -importcert -noprompt -alias ${INTERMEDIATE_BUNDLE} -file ${SSL_CERT_DIR}/${INTERMEDIATE_BUNDLE} -keystore ${JAVA_KEYSTORE} -storepass ${JAVA_KEYSTORE_PASSWORD} >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1 | exit 0)
 	
 	# get the DataONE CA
 	
@@ -1149,11 +1152,11 @@ function configure_apache()
 		fi
 		
 		## Set the server side SSL CA bundle
-		local INTERMEDIATE_BUNDLE="${DEB_QUESTION_VALUES[dataone-cn-os-core/cn.server.cachain.filename]}"
+		#local INTERMEDIATE_BUNDLE="${DEB_QUESTION_VALUES[dataone-cn-os-core/cn.server.cachain.filename]}"
 
-		if ! (sed -i.bak  's/INTERMEDIATE_BUNDLE/'${INTERMEDIATE_BUNDLE}'/' ${APACHE_CONF_DIR}/sites-available/${SITE}.conf >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
-			log "Unable to modify INTERMEDIATE_BUNDLE in ${SITE}.conf Apache"
-		fi
+		#if ! (sed -i.bak  's/INTERMEDIATE_BUNDLE/'${INTERMEDIATE_BUNDLE}'/' ${APACHE_CONF_DIR}/sites-available/${SITE}.conf >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+			#log "Unable to modify INTERMEDIATE_BUNDLE in ${SITE}.conf Apache"
+		#fi
 
 		
 		## Set the client side SSL CA chain file            
@@ -1162,7 +1165,7 @@ function configure_apache()
 		fi
 		
 		## Set the client side SSL certificate file            
-		if ! (sed -i.bak  's/PUBLIC_SERVER_CERT/'${DEB_QUESTION_VALUES[dataone-cn-os-core/cn.server.publiccert.filename]}'/' ${APACHE_CONF_DIR}/sites-available/${SITE}.conf >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+		if ! (sed -i.bak  's/CN_HOSTNAME/'${DEB_QUESTION_VALUES[dataone-cn-os-core/cn.hostname]}'/' ${APACHE_CONF_DIR}/sites-available/${SITE}.conf >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
 			log "Unable to modify PUBLIC_SERVER_CERT_FILE in ${SITE}.conf Apache"
 		fi
 		
