Redirect the ouput of the rm command to the log file.

diff --git a/DEBIAN/postinst b/DEBIAN/postinst
--- a/DEBIAN/postinst
+++ b/DEBIAN/postinst
@@ -1748,16 +1748,20 @@ function configure_bouncycastle()
 	else
 		echo "bouncycastle security provider was previously installed "
 		if [ -e ${JAVA_SECURITY_EXT_DIR}/bcprov-jdk16-1.46.jar ]; then
-			echo "but we need to upgrade the bcprov-jdk16-1.46.jar file"
-			rm ${JAVA_SECURITY_EXT_DIR}/bcprov-jdk16-1.46.jar
+			echo "but we need to upgrade the bcprov-jdk16-1.46.jar file"	
+			if ! (rm ${JAVA_SECURITY_EXT_DIR}/bcprov-jdk16-1.46.jar >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+				log "Removing ${JAVA_SECURITY_EXT_DIR}/bcprov-jdk16-1.46.jar failed"
+			fi
 			if ! (cp ${SOURCE_DIR}/bcprov-jdk15on-1.46.jar ${JAVA_SECURITY_EXT_DIR} >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
 				log "Copy of ${SOURCE_DIR}/bcprov-jdk15on-1.46.jar to ${JAVA_SECURITY_EXT_DIR} failed"
 			fi
 			
 		fi
 		if [ -e ${JAVA_SECURITY_EXT_DIR}/bcmail-jdk16-1.46.jar ]; then
-			echo "but we need to upgrade the bcmail-jdk16-1.46.jar file"
-			rm ${JAVA_SECURITY_EXT_DIR}/bcmail-jdk16-1.46.jar
+			echo "but we need to upgrade the bcmail-jdk16-1.46.jar file"		
+			if ! (rm ${JAVA_SECURITY_EXT_DIR}/bcmail-jdk16-1.46.jar >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+				log "Removing ${JAVA_SECURITY_EXT_DIR}/bcmail-jdk16-1.46.jar failed"
+			fi
 			if ! (cp ${SOURCE_DIR}/bcmail-jdk15on-1.46.jar ${JAVA_SECURITY_EXT_DIR} >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
 				log "Copy of ${SOURCE_DIR}/bcmail-jdk15on-1.46.jar to ${JAVA_SECURITY_EXT_DIR} failed"
 			fi
