closes #7385
added in functionality for mod qos configuration

diff --git a/DEBIAN/postinst b/DEBIAN/postinst
--- a/DEBIAN/postinst
+++ b/DEBIAN/postinst
@@ -87,6 +87,7 @@ SOURCE_DIR=/usr/share/dataone-cn-os-core
 SCRIPT_DIR=${SOURCE_DIR}/debian
 APACHE_CONF_DIR=/etc/apache2
 MOD_JK_CONF_DIR=/etc/libapache2-mod-jk
+APACHE_WWW_DIR=/var/www
 D1_CONF_DIR=/etc/dataone
 NODE_PROPS="$D1_CONF_DIR/node.properties"
 LDAP_CONF_DIR=/etc/ldap
@@ -963,6 +964,15 @@ function configure_apache()
 		log "Unable to copy ${SCRIPT_DIR}/workers.properties to ${MOD_JK_CONF_DIR}/"
 	fi
 	
+	log "Copying qos to ${APACHE_CONF_DIR}/mods-available/"
+	if ! (cp ${SCRIPT_DIR}/qos ${APACHE_CONF_DIR}/conf.d/ >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+		log "Unable to copy ${SCRIPT_DIR}/qos to ${APACHE_CONF_DIR}/conf/"
+	fi
+	log "Copying mod_qos_500_error.xml to ${APACHE_CONF_DIR}/mods-available/"
+	if ! (cp ${SCRIPT_DIR}/mod_qos_500_error.xml ${APACHE_WWW_DIR}/ >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+		log "Unable to copy ${SCRIPT_DIR}/mod_qos_500_error.xml to ${APACHE_WWW_DIR}/"
+	fi
+	
 	## disable and then re-enable mod_proxy, mod_rewrite, and mod_headers
 	log "Refreshing Proxy"	
 	if ! (a2dismod proxy_ajp >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
@@ -1010,6 +1020,14 @@ function configure_apache()
 		log "Unable to enable ssl site"
 	fi
 	
+	## disable and then re-enable mod qos to pick up changes
+	log "Refreshing Mod QoS"
+	if ! (a2dismod qos >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+		log "Unable to disable mod qos"
+	fi
+	if ! (a2enmod qos >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+		log "Unable to enable mod qos"
+	fi
 	## disable and then re-enable mod jk to pick up changes
 	log "Refreshing Mod JK"
 	if ! (a2dismod jk >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
@@ -1019,9 +1037,24 @@ function configure_apache()
 		log "Unable to enable jk apache site"
 	fi
 	
+
+
 	## disable the default apache site, which gets in the way of the other sites
 	if ! (a2dissite 000-default >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
 		log "Unable to disable  000-default apache site"
+	fi
+	
+	## mod_qos needs to be modified to add in exclusions for all the CNs
+	# in this environment
+	local MOD_QOS_CN_EXCLUSIONS="\n"
+	if [[ "${DEB_QUESTION_VALUES[dataone-cn-os-core/cn.iplist]}" == [1-9]* ]]; then
+		for IP in ${DEB_QUESTION_VALUES[dataone-cn-os-core/cn.iplist]}
+			do
+				MOD_QOS_CN_EXCLUSIONS+="\tQS_SrvMaxConnExcludeIP\t${IP}\n"
+			done
+		if ! (sed -i  's/CN_QS_SRVMAXCONNEXCLUDEIP/'${MOD_QOS_CN_EXCLUSIONS}'/' ${APACHE_CONF_DIR}/conf.d/qos >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+			log "Unable to configure apache mod_qos to exclude CNs"
+		fi
 	fi
 	
 	## copy in site configuration files
