merge from 2.0 branch: enable disk_cache mod. https://redmine.dataone.org/issues/7562

diff --git a/DEBIAN/postinst b/DEBIAN/postinst
--- a/DEBIAN/postinst
+++ b/DEBIAN/postinst
@@ -1017,6 +1017,14 @@ function configure_apache()
 		log "Unable to ensable headers apache module"
 	fi
 	
+	log "Refreshing Cache module"
+	if ! (a2dismod disk_cache >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+		log "Unable to disable apache disk_cache module"
+	fi
+	if ! (a2enmod disk_cache >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+		log "Unable to enable apache disk_cache module"
+	fi
+	
 	# Turn on the ssl module
 	log "Refreshing Mod SSL"
 	if ! (a2dismod ssl >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
