moving a couple ldap population commands up in the install order

diff --git a/DEBIAN/postinst b/DEBIAN/postinst
--- a/DEBIAN/postinst
+++ b/DEBIAN/postinst
@@ -1287,22 +1287,23 @@ function configure_openldap()
 				exitWithFailureCode 73
 			fi
 		fi
+		if ! (sudo ldapsearch -Y EXTERNAL -H ldapi:/// -b 'cn=module{0},cn=config' >/dev/null 2>&1 ); then
+			if ! (sudo ldapadd -Y EXTERNAL -H ldapi:/// -f ${SCRIPT_DIR}/ldap/backendDBConfig.ldif  >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+				log "ldapadd backendDBConfig.ldif failed. Unable to continue"
+				exitWithFailureCode 74
+			fi
+		fi
+		log "Adding dataone schema specific entries"
+		if ! (sudo ldapsearch -Y EXTERNAL -H ldapi:/// -b 'dc=org'  >/dev/null 2>&1 ); then
+			if ! (sudo ldapadd -Y EXTERNAL -H ldapi:/// -f ${SCRIPT_DIR}/ldap/org.ldif >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+				log "ldapadd org.ldif failed. Unable to continue"
+				exitWithFailureCode 75
+			fi
+		fi
 		if [ "${DEB_QUESTION_VALUES[dataone-cn-os-core/cn.openldap.firstcn]}" == "true" ]; then
 			log "This is the first CN to be installed in the environment"
 
-			if ! (sudo ldapsearch -Y EXTERNAL -H ldapi:/// -b 'cn=module{0},cn=config' >/dev/null 2>&1 ); then
-				if ! (sudo ldapadd -Y EXTERNAL -H ldapi:/// -f ${SCRIPT_DIR}/ldap/backendDBConfig.ldif  >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
-					log "ldapadd backendDBConfig.ldif failed. Unable to continue"
-					exitWithFailureCode 74
-				fi
-			fi
-			log "Adding dataone schema specific entries"
-			if ! (sudo ldapsearch -Y EXTERNAL -H ldapi:/// -b 'dc=org'  >/dev/null 2>&1 ); then
-				if ! (sudo ldapadd -Y EXTERNAL -H ldapi:/// -f ${SCRIPT_DIR}/ldap/org.ldif >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
-					log "ldapadd org.ldif failed. Unable to continue"
-					exitWithFailureCode 75
-				fi
-			fi
+
 			if ! (sudo ldapsearch -Y EXTERNAL -H ldapi:/// -b 'dc=dataone,dc=org' >/dev/null 2>&1 ); then
 				if ! (sudo ldapadd -Y EXTERNAL -H ldapi:/// -f ${SCRIPT_DIR}/ldap/dataone.ldif >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
 					log "ldapadd dataone.ldif failed. Unable to continue"
