Remove the code to set ulimit on /etc/init.d/tomcat8

diff --git a/DEBIAN/postinst b/DEBIAN/postinst
--- a/DEBIAN/postinst
+++ b/DEBIAN/postinst
@@ -1235,14 +1235,14 @@ function configure_tomcat()
 				#fi
 			#fi
 		#fi
-		if ! (egrep -q 'ulimit.+\-Hn' /etc/init.d/tomcat8); then
-			if ! (sed -i.bak --regexp-extended 's/^(\#\!\/bin\/sh.*$)/\1\n  ulimit -Hn 16384\n  ulimit -Sn 16384\n/;' /etc/init.d/tomcat8 >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
-				log "Unable to modify ulimit in /etc/init.d/tomcat8"
-			fi
-			if ! (rm /etc/init.d/tomcat8.bak >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
-				log "Unable to remove /etc/init.d/tomcat8.bak"
-			fi
-		fi
+		#if ! (egrep -q 'ulimit.+\-Hn' /etc/init.d/tomcat8); then
+		#	if ! (sed -i.bak --regexp-extended 's/^(\#\!\/bin\/sh.*$)/\1\n  ulimit -Hn 16384\n  ulimit -Sn 16384\n/;' /etc/init.d/tomcat8 >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+		#		log "Unable to modify ulimit in /etc/init.d/tomcat8"
+		#	fi
+		#	if ! (rm /etc/init.d/tomcat8.bak >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+		#		log "Unable to remove /etc/init.d/tomcat8.bak"
+		#	fi
+		#fi
 	fi
 	
 	if [ -e "/etc/default/tomcat8" ]; then
@@ -1263,22 +1263,17 @@ function configure_tomcat()
 				fi
 			fi
 		fi
-		if ! (egrep -q 'JAVA_OPTS\=.+\-Xmx' /etc/default/tomcat8); then
-			log "THERE WAS AN ERROR /etc/init.d/tomcat NO LONGER HAS -Xmx DEFINED"
-			## -Xmx is not set, that is bad, the tomcat installation must
-			## have change significantly. We must manually add it to the JAVA_OPTS LINE
-			## and then change this script to handle the exact line to add it to
-			
-		else 
-			if ! (egrep -q 'JAVA_OPTS\=.+\-XX\:MaxPermSize' /etc/default/tomcat8); then
+		
+		if ! (egrep -q 'JAVA_OPTS\=.+\-XX\:MaxPermSize' /etc/default/tomcat8); then
 				## THE MAIN PROBLEM WITH THIS APPROACH CURRENTLY IS SUPPORTING THE DIFFERENT ENVIRONEMENTS
 				## developer VMs will not be able to support this amount of heap space
 				## in fact our development environment probably cannot
-				if ! (sed -i.bak --regexp-extended 's/(^JAVA_OPTS\=)"([^"]*)"/\1"\2 -Xmx8192M -Xms1024M -XX:MaxPermSize=512M"/;' /etc/default/tomcat8 >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+				log "Can't find the memory setting on /etc/default/tomcat8, then set them."
+				if ! (sed -i.bak --regexp-extended '0,/(^JAVA_OPTS\=)"([^"]*)"/s//\1"\2 -Xmx8192M -Xms1024M -XX:MaxPermSize=512M"/;' /etc/default/tomcat8 >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
 					log "Unable to modify heap space settings in /etc/default/tomcat8"
 				fi
-			fi
 		fi
+		
 	fi
 	## copy in jk.conf file
 	if [ -e "${TOMCAT_HOME}/conf/server.xml" ]; then 
