refs #7564   the token SEARCH_SERVER_NAME was switched to SEARCH_HOSTNAME since another occurrance of the string SERVER_NAME was substituted before the sed call to replace SEARCH_SERVER_NAME (the string SERVER_NAME in  SEARCH_SERVER_NAME token matches in the postinst script an earlier sed for the token SERVER_NAME)

diff --git a/DEBIAN/postinst b/DEBIAN/postinst
--- a/DEBIAN/postinst
+++ b/DEBIAN/postinst
@@ -1112,8 +1112,8 @@ function configure_apache()
 		## replace the token SEARCH_SERVER_NAME in the site file
 		
 		if [ -n ${DEB_QUESTION_VALUES[dataone-cn-os-core/cn.search.hostname]} ]; then
-			if ! (sed -i.bak  's/SEARCH_SERVER_NAME/'${DEB_QUESTION_VALUES[dataone-cn-os-core/cn.search.hostname]}'/' ${APACHE_CONF_DIR}/sites-available/${SITE} >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
-				log "Unable to modify SEARCH_SERVER_NAME in ${SITE} Apache"
+			if ! (sed -i.bak  's/SEARCH_HOSTNAME/'${DEB_QUESTION_VALUES[dataone-cn-os-core/cn.search.hostname]}'/' ${APACHE_CONF_DIR}/sites-available/${SITE} >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+				log "Unable to modify SEARCH_NAME in ${SITE} Apache"
 			fi
 		else
 				log "dataone-cn-os-core/cn.router.hostname can not be set in ${APACHE_CONF_DIR}/sites-available/${SITE}"
