merge from branch: add handling for search UI redirects for each environment in the buildout. https://redmine.dataone.org/issues/7561 also include caching directives from branch: https://redmine.dataone.org/issues/7562

diff --git a/DEBIAN/postinst b/DEBIAN/postinst
--- a/DEBIAN/postinst
+++ b/DEBIAN/postinst
@@ -1101,6 +1101,16 @@ function configure_apache()
 				log "dataone-cn-os-core/cn.hostname can not be set in ${APACHE_CONF_DIR}/sites-available/${SITE}"
 		fi
 		
+		## replace the token SEARCH_SERVER_NAME in the site file
+		
+		if [ -n ${DEB_QUESTION_VALUES[dataone-cn-os-core/cn.search.hostname]} ]; then
+			if ! (sed -i.bak  's/SEARCH_SERVER_NAME/'${DEB_QUESTION_VALUES[dataone-cn-os-core/cn.search.hostname]}'/' ${APACHE_CONF_DIR}/sites-available/${SITE} >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+				log "Unable to modify SEARCH_SERVER_NAME in ${SITE} Apache"
+			fi
+		else
+				log "dataone-cn-os-core/cn.router.hostname can not be set in ${APACHE_CONF_DIR}/sites-available/${SITE}"
+		fi
+		
 		## Set the server side SSL CA bundle
 		local INTERMEDIATE_BUNDLE="${DEB_QUESTION_VALUES[dataone-cn-os-core/cn.server.cachain.filename]}"
 
